SET(ARCH arm)
SET(SYSTEM 3ds9)
SET(LOWEST_CPU arm946e-s)
SET(ENABLE_THUMB 1)
SET(ENABLE_EXTRA_MEMORY 1)
SET(DRIVER_SRCS ${DRIVER_SRCS} hw/framebuffer/*.c hw/framebuffer/*.cpp hw/framebuffer/*.s)
SET(DRIVER_SRCS ${DRIVER_SRCS} hw/3ds9/picafb/*.c hw/3ds9/picafb/*.cpp hw/3ds9/picafb/*.s)
SET(DRIVER_SRCS ${DRIVER_SRCS} hw/3ds9/vectorinit/*.c hw/3ds9/vectorinit/*.cpp hw/3ds9/vectorinit/*.s)
SET(DRIVER_SRCS ${DRIVER_SRCS} hw/pmm/*.c hw/pmm/*.cpp hw/pmm/*.s)
